class ForgeException(Exception):
    pass

class UnexpectedCall(ForgeException):
    pass


